name: oak
version: '0.0.0.1'
synopsis: A reactive server-side application framework + tookit for Haskell
description: Please see README.md
category: Web
author: Mario Rogic
maintainer: hello@mario.net.au
copyright: 2016-present Mario Rogic
license: GPL-3
github: supermario/oak
default-extensions:
- OverloadedStrings
- RecordWildCards

dependencies:
- text

library:
  source-dirs:
  - src
  - evergreen
  exposed-modules:
  - App
  - AstDatabase
  - AstHelpers
  - AstMigration
  - AstMigrations
  - AstSchema
  - Evergreen
  - MigrationHelpers
  - Migrations
  - Oak
  - OakRuntime
  - ShellHelpers

  dependencies:
  - ansi-wl-pprint
  - base >=4.7 && <5
  - bytestring
  - cache
  - containers
  - cryptonite
  - foldl
  - hashable
  - haskell-src-exts-simple
  - hilt
  - postgresql-orm
  - postgresql-simple
  - random
  - safe
  - slave-thread
  - stm
  - time
  - turtle
  - unagi-chan


executables:
  oak-example:
    main: Run.hs
    source-dirs: examples/
    dependencies:
    - base
    - oak
  eg:
    main: Cli.hs
    source-dirs:
    - cli/
    dependencies:
    - base
    - bytestring
    - foldl
    - haskell-src-exts-simple
    - hilt
    - oak
    - postgresql-orm
    - postgresql-simple
    - system-filepath
    - time
    - turtle


tests:
  test:
    main: Main.hs
    source-dirs: test/
    ghc-options: -Wall
    dependencies:
    - base
    - hspec
