name: oak
version: '0.0.0.1'
synopsis: A reactive server-side application framework + tookit for Haskell
description: Please see README.md
category: Web
author: Mario Rogic
maintainer: hello@mario.net.au
copyright: 2016-present Mario Rogic
license: GPL-3
github: supermario/oak
default-extensions:
- OverloadedStrings
- RecordWildCards

dependencies:
- text

library:
  source-dirs:
  - src
  - evergreen
  - evergreen/seasons
  exposed-modules:
  - Oak
  - OakRuntime
  - App
  - Migrations
  - MigrationHelpers
  - Evergreen
  dependencies:
  - base >=4.7 && <5
  - bytestring
  - cache
  - hashable
  - hilt
  - postgresql-orm
  - postgresql-simple
  - random
  - slave-thread
  - stm
  - unagi-chan


executables:
  oak-example:
    main: Run.hs
    source-dirs: examples/
    dependencies:
    - base
    - oak
  eg:
    main: Cli.hs
    source-dirs:
    - cli/

    dependencies:
    - ansi-wl-pprint
    - base
    - bytestring
    - containers
    - cryptonite
    - foldl
    - haskell-src-exts-simple
    - hilt
    - oak
    - postgresql-orm
    - postgresql-simple
    - safe
    - system-filepath
    - time
    - turtle

tests:
  test:
    main: Main.hs
    source-dirs: test/
    ghc-options: -Wall
    dependencies:
    - base
    - hspec
