resolver: lts-9.17

packages:
- '.'
# - '../hilt'

extra-deps:
- heroku-0.1.2.3
- heroku-persistent-0.2.0
- postgresql-simple-url-0.1.0.1
- unagi-chan-0.4.0.0
- haskell-src-exts-1.19.1
- haskell-src-exts-simple-1.19.0.0
- postgresql-orm-0.5.0
- git: git@github.com:supermario/hilt.git
  commit: 9dbf9431a6b8fcff2134e7a7c1b88cd71512fc03

flags: {}

extra-package-dbs: []
