resolver: lts-8.23

packages:
- '.'
- location:
    git: git@github.com:supermario/hilt.git
    commit: ae4a54f9fde56015dce8de83cd0935e5e5776eeb

extra-deps:
- heroku-0.1.2.3
- heroku-persistent-0.2.0
- postgresql-simple-url-0.1.0.1
- unagi-chan-0.4.0.0
- haskell-src-exts-1.19.1
- haskell-src-exts-simple-1.19.0.0
- postgresql-orm-0.5.0

flags: {}

extra-package-dbs: []
