resolver: lts-7.24

packages:
- '.'
- location:
    git: https://github.com/supermario/hilt.git
    commit: f2346ae

extra-deps:
- heroku-0.1.2.3
- heroku-persistent-0.2.0
- http-dispatch-0.5.0.2
- postgresql-simple-url-0.1.0.1
- unagi-chan-0.4.0.0

flags: {}

extra-package-dbs: []
