resolver: lts-8.22

packages:
- '.'
- location:
    git: https://github.com/supermario/hilt.git
    commit: 3c3add0

extra-deps:
- heroku-0.1.2.3
- heroku-persistent-0.2.0
- postgresql-simple-url-0.1.0.1
- unagi-chan-0.4.0.0

flags: {}

extra-package-dbs: []
