resolver: lts-10.3

packages:
- '.'
# - '../hilt'

extra-deps:
- unagi-chan-0.4.0.0
- haskell-src-exts-1.19.1
- haskell-src-exts-simple-1.19.0.0
- postgresql-orm-0.5.0
- git: git@github.com:supermario/hilt.git
  commit: f59eff3a1b4d2d897ddd1ce94c8f7e9a6b4eefea

flags: {}

extra-package-dbs: []
